sudo: required
services:
  - docker
before_install:
  - docker build -t wynetech/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true wynetech/react-test -react npm run test -- --coverage
after_success:
  - docker build -t wynetech/multi-client ./client
  - docker build -t wynetech/multi-nginx ./nginx
  - docker build -t wynetech/multi-server ./server
  - docker build -t wynetech/multi-worker ./worker
  #login into docker-cli
  - echo "$DOCKER_PASSWORD" | docker lgin -u "DOCKER_ID" --password-stdin
  - docker push wynetech/multi-client
  - docker push wynetech/multi-nginx
  - docker push wynetech/multi-server
  - docker push wynetech/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docer"
